In [1]:
import numpy as np

In [6]:
#1 A
A = np.array ([[2,5,5], [-1,-1,0], [2,4,3]])
A

array([[ 2,  5,  5],
       [-1, -1,  0],
       [ 2,  4,  3]])

In [4]:
np.linalg.det(A) #det(A) é -1, ou seja tem inversa (diferente de 0)

-1.0000000000000002

In [5]:
#calculando a inversa da matriz A

np.linalg.inv(A)

array([[ 3., -5., -5.],
       [-3.,  4.,  5.],
       [ 2., -2., -3.]])

In [7]:
# 1 B
C = np.array ([[1,-1,0,3], [2,5,2,6], [0,1,0,0], [1,4,2,1]])
C

array([[ 1, -1,  0,  3],
       [ 2,  5,  2,  6],
       [ 0,  1,  0,  0],
       [ 1,  4,  2,  1]])

In [9]:
np.linalg.det(C) #det(C) é 4, ou seja tem inversa (diferente de 0)

4.000000000000001

In [10]:
#calculando a inversa da matriz C

np.linalg.inv(C)

array([[ 2.5, -1.5,  4. ,  1.5],
       [-0. , -0. ,  1. , -0. ],
       [-1. ,  0.5, -3.5,  0. ],
       [-0.5,  0.5, -1. , -0.5]])

In [11]:
#2 A
a = np.array ([[1,4,5], [2,-1,2], [3,0,3]])
a

array([[ 1,  4,  5],
       [ 2, -1,  2],
       [ 3,  0,  3]])

In [14]:
np.linalg.det(a) #determinante de a

12.0

In [13]:
#2 B
b= np.array ([[6,-2,5], [2,1,2], [3,-2,3]])
b

array([[ 6, -2,  5],
       [ 2,  1,  2],
       [ 3, -2,  3]])

In [15]:
np.linalg.det(b) #determinante de b

6.999999999999999