# Assuntos:
* Matriz transposta
* Matriz inversa
* Matriz identidade

## Matriz transposta: 
* É uma matriz que troca as linhas pelas colunas de uma matriz. Se uma matriz **A** tem dimensão 3x2, ápos ser tranposta $A^t$ será 2x3.
* Uma matriz transposta da transposta $(A^t)^t$, volta a ser a matriz original.
* A transposta da soma de duas matrizes é igual à soma das transpostas de cada matriz: $(A+B)^t = A^t + B^t$.
  
Exemplo de matriz transposta abaixo:

In [5]:
import numpy as np

matriz = np.array ([[1,1,-3], [2,1,3], [2,0,-1]])

In [6]:
matriz

array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [7]:
matriz.transpose() #jeito 1

array([[ 1,  2,  2],
       [ 1,  1,  0],
       [-3,  3, -1]])

In [9]:
matriz.T #jeito 2 (mais pratico)

array([[ 1,  2,  2],
       [ 1,  1,  0],
       [-3,  3, -1]])

## Matriz inversa
* É uma matriz que **é obtida a partir de uma matriz quadrada** A, tal que o produto entre A e sua inversa resulta na matriz identidade.
* A inversa é denotada por $A^{-1}$
* Para calcular é necessário que o determinante de A seja diferente de zero
* A inversa da inversa de uma matriz é igual a matriz original, $(A^{-1})^{-1}$
* Determinante tem que ser diferente de zero, $det(A)\neq 0$

Exemplo de matriz inversa abaixo:


In [10]:
A = matriz
A

array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [11]:
#Para matriz A ter matriz inversa:
#matriz original tem que ser quadrada: 3x3
#determinante da original, tem que ser diferente de zero

np.linalg.det(A) #det(A) é 13, ou seja tem inversa (diferente de 0)

13.0

In [12]:
#calculando ainversa da matriz A

np.linalg.inv(A)

array([[-0.07692308,  0.07692308,  0.46153846],
       [ 0.61538462,  0.38461538, -0.69230769],
       [-0.15384615,  0.15384615, -0.07692308]])

In [14]:
A_inv = np.linalg.inv(A) #matriz inversa
np.dot (A, A_inv) #resulta a matriz identidade

array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

## Matriz identidade
* É uma matriz quadrada em que os elementos na **diagonal principal são iguais a 1** e os demais elementos iguais a 0.
* A representação é I<sub>n</sub>
* O produto entre uma matriz quadrada A e sua matriz identidade correspondente é igual à própria matriz A:
  
  **A . I <sub>n</sub> = I<sub>n</sub> . A = A**
* O produto entre uma matriz quadrada A e sua matriz inversa correspondente é igual à matriz identidade:

  **A . $A^{-1}$ = $A^{-1}$ . A = I<sub>n</sub>**
