In [2]:
matriz_A = [[1,2,3],[4,5,6]]

In [3]:
matriz_A

[[1, 2, 3], [4, 5, 6]]

In [5]:
matriz_A[0] #acessando a primeira linha ---> no python o indice começa no zero

[1, 2, 3]

In [6]:
matriz_A[1] #acessando a segunda linha

[4, 5, 6]

In [7]:
matriz_A [0][1] #elemento da primeira linha segunda coluna

2

# NumPy Array: 
* É um pacote para computação científica que fornece ampla gama de funções e métodos para trabalhar com matrizes multidimensionais.



In [9]:
import numpy as np

* Dentro do numpy, temos o método 'array', onde passamos uma lista bi-dimensional (listas de listas) e ele nos gera a matriz. O exemplo abaixo mostra que criamos uma matriz 3x3.

In [11]:
matriz_B = np.array ([[1,2,3],[4,5,6], [7,8,9]])

print(matriz_B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
matriz_B[0] #acessando a primeira linha

array([1, 2, 3])

In [13]:
matriz_B[1] #acessando a segunda linha

array([4, 5, 6])

In [14]:
matriz_B[2][1] #acessar a terceira linha e segunda coluna

8

Algumas operações que podemos realizar usando o NumPy
* Transposição de matriz: é uma operação que troca as linhas e colunas da matriz. Exemplo abaixo:

In [15]:
matriz_transposta = matriz_B.transpose()
matriz_transposta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

* Adição de matrizes: a adição e subtração são realizadas elemento por elemento. Para que ocorra a adição/subtração, elas devem ter a mesma dimensão. Exemplo abaixo:

In [16]:
matriz1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
matriz2 = np.array([[9,8,7],[6,5,4], [3,2,1]])
matriz1+matriz2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

* Subtração de matrizes

In [18]:
matriz1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
matriz2 = np.array([[9,8,7],[6,5,4], [3,2,1]])
matriz1-matriz2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

* Multiplicação de matrizes: é definida apenas se o número de colunas A for igual ao número de linhas de B. O resultado é uma matriz C, onde o elemento na linha i e coluna j é o produto escalar da linha i de A e da coluna j de B.

In [19]:
matriz1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
matriz2 = np.array([[9,8,7],[6,5,4], [3,2,1]])
matriz1*matriz2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])